create table if not exists teams (
  id bigint generated by default as identity primary key,
  team_name text not null,
  logo_url text,
  base_country text,
  championships integer default 0,
  active_years text
);

create table if not exists drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  nationality text,
  birthdate text,
  profile_image_url text,
  championships integer default 0,
  wins integer default 0,
  podiums integer default 0,
  poles integer default 0,
  fastest_laps integer default 0,
  biography text
);

create table if not exists driver_teams (
  driver_id bigint not null references drivers(id) on delete cascade,
  team_id bigint not null references teams(id) on delete cascade,
  primary key (driver_id, team_id)
);

create table if not exists circuits (
  id bigint generated by default as identity primary key,
  circuit_name text not null,
  country text,
  track_layout_url text,
  lap_length_km numeric,
  first_gp_year integer
);

create table if not exists seasons (
  id bigint generated by default as identity primary key,
  year integer not null,
  champion_driver_id bigint references drivers(id) on delete set null,
  champion_team_id bigint references teams(id) on delete set null,
  total_races integer default 0,
  banner_image_url text
);

create table if not exists races (
  id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(id) on delete cascade,
  circuit_id bigint not null references circuits(id) on delete cascade,
  winner_driver_id bigint references drivers(id) on delete set null,
  second_driver_id bigint references drivers(id) on delete set null,
  third_driver_id bigint references drivers(id) on delete set null,
  fastest_lap_driver_id bigint references drivers(id) on delete set null,
  laps integer
);

create table if not exists race_results_positions (
  id bigint generated by default as identity primary key,
  race_id bigint not null references races(id) on delete cascade,
  driver_id bigint not null references drivers(id) on delete cascade,
  team_id bigint references teams(id) on delete set null,
  position integer not null,
  points numeric not null default 0,
  laps integer,
  time text,
  status text not null default 'Finished',
  unique (race_id, position),
  unique (race_id, driver_id)
);

create table if not exists media (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  category text,
  caption text
);

create table if not exists driver_standings (
  id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(id) on delete cascade,
  driver_id bigint not null references drivers(id) on delete cascade,
  team_id bigint references teams(id) on delete set null,
  position integer not null,
  points numeric not null default 0,
  wins integer not null default 0,
  unique (season_id, driver_id)
);

create table if not exists constructor_standings (
  id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(id) on delete cascade,
  team_id bigint not null references teams(id) on delete cascade,
  position integer not null,
  points numeric not null default 0,
  wins integer not null default 0,
  unique (season_id, team_id)
);

create table if not exists timeline_events (
  id bigint generated by default as identity primary key,
  year integer not null,
  title text not null,
  description text,
  image_url text
);

-- RLS: enable and allow read for public, write for authenticated.
alter table teams enable row level security;
alter table drivers enable row level security;
alter table driver_teams enable row level security;
alter table circuits enable row level security;
alter table seasons enable row level security;
alter table races enable row level security;
alter table race_results_positions enable row level security;
alter table media enable row level security;
alter table driver_standings enable row level security;
alter table constructor_standings enable row level security;
alter table timeline_events enable row level security;

drop policy if exists "Public read" on teams;
drop policy if exists "Public read" on drivers;
drop policy if exists "Public read" on driver_teams;
drop policy if exists "Public read" on circuits;
drop policy if exists "Public read" on seasons;
drop policy if exists "Public read" on races;
drop policy if exists "Public read" on race_results_positions;
drop policy if exists "Public read" on media;
drop policy if exists "Public read" on driver_standings;
drop policy if exists "Public read" on constructor_standings;
drop policy if exists "Public read" on timeline_events;

create policy "Public read" on teams for select using (true);
create policy "Public read" on drivers for select using (true);
create policy "Public read" on driver_teams for select using (true);
create policy "Public read" on circuits for select using (true);
create policy "Public read" on seasons for select using (true);
create policy "Public read" on races for select using (true);
create policy "Public read" on race_results_positions for select using (true);
create policy "Public read" on media for select using (true);
create policy "Public read" on driver_standings for select using (true);
create policy "Public read" on constructor_standings for select using (true);
create policy "Public read" on timeline_events for select using (true);

drop policy if exists "Admin write" on teams;
drop policy if exists "Admin write" on drivers;
drop policy if exists "Admin write" on driver_teams;
drop policy if exists "Admin write" on circuits;
drop policy if exists "Admin write" on seasons;
drop policy if exists "Admin write" on races;
drop policy if exists "Admin write" on race_results_positions;
drop policy if exists "Admin write" on media;
drop policy if exists "Admin write" on driver_standings;
drop policy if exists "Admin write" on constructor_standings;
drop policy if exists "Admin write" on timeline_events;

create policy "Admin write" on teams
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on drivers
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on driver_teams
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on circuits
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on seasons
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on races
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on race_results_positions
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on media
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on driver_standings
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on constructor_standings
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admin write" on timeline_events
  for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
